<?php

namespace ContainerVhusvKV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApplicationService extends App_AppKernelDevDebugContainer
{
    /**
     * Gets the public 'Symfony\Component\Console\Application' shared autowired service.
     *
     * @return \Symfony\Component\Console\Application
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/service-contracts/ResetInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Application.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Console/Command/CreateUserCommand.php';

        $container->services['Symfony\\Component\\Console\\Application'] = $instance = new \Symfony\Component\Console\Application();

        $instance->add(new \App\Console\Command\CreateUserCommand());

        return $instance;
    }
}
