<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVhusvKV\App_AppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVhusvKV/App_AppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVhusvKV.legacy');

    return;
}

if (!\class_exists(App_AppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVhusvKV\App_AppKernelDevDebugContainer::class, App_AppKernelDevDebugContainer::class, false);
}

return new \ContainerVhusvKV\App_AppKernelDevDebugContainer([
    'container.build_hash' => 'VhusvKV',
    'container.build_id' => '51c25da0',
    'container.build_time' => 1641914085,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVhusvKV');
